expansion:
  uspto:
    - /home/shizuku/Peptide_to_small_molecule/aizynthfinder_data/uspto_model.onnx
    - /home/shizuku/Peptide_to_small_molecule/aizynthfinder_data/uspto_templates.csv.gz
  ringbreaker:
    - /home/shizuku/Peptide_to_small_molecule/aizynthfinder_data/uspto_ringbreaker_model.onnx
    - /home/shizuku/Peptide_to_small_molecule/aizynthfinder_data/uspto_ringbreaker_templates.csv.gz
filter:
  uspto: /home/shizuku/Peptide_to_small_molecule/aizynthfinder_data/uspto_filter_model.onnx
stock:
  zinc: /home/shizuku/Peptide_to_small_molecule/aizynthfinder_data/zinc_stock.hdf5
